--删除表中的重复数据

select distinct 
DAY_KEY
,hour_key
,CITY_CODE
,tac
,NUMOFATTACHSUCC
,NUMOFATTACH
,TAU_SUCC_CNT
,TAU_CNT
,E_RAB_SUCC_CNT
,E_RAB_REQ_CNT
,PAGING_SUCC_CNT
,PAGING_REQ_CNT
,UE_CONNECT_SUCC_CNT
,UE_CONNECT_REQ_CNT
,UE_NET_SUCC_CNT
,UE_NET_REQ_CNT
,UE_CONNECT_ABNORMAL_FZ
,UE_CONNECT_ABNORMAL_FM
,SERVICE_SUCC_PS_CNT
,SERVICE_REQ_PS_CNT
,USER_FLOW_UP_NEW
,USER_FLOW_DN_NEW
,TCPACK
,TCPSYNACK
,TCP_23SH_LATENCY_SUM
,TCP_23SH_LATENCY_CNT
,PACKETDISORDER
,PACKETRETRANS
,PACKETIP
,SESSREQ
,SESSFAIL
,SESS_RES_LATENCY_SUM
,SESS_RES_LATENCY_CNT
,SESSREQ_2K
,SESSFAIL_2K
,SESS_RES_LATENCY_SUM_2K
,SESS_RES_LATENCY_CNT_2K
,DL_TRAFFIC_2K
,DL_ONLINETIME_2K
,DL_ONLINETIME_50K
,DL_TRAFFIC_50K
,DL_TRAFFIC_500
,DL_TRAFFIC_500_DELAY
,ONLINETIMED
,TCP_12SH_LATENCY
,TCP_CON_LATENCY
,TCP_REQ_CNT
,TCP_SUCC_CNT
,ATTACH_LATENCY_SUM
,SESS_LATENCY_SUM_2K
,SESS_LATENCY_CNT_2K
,BEARE_CON_LATENCY_SUM
,DL_TRAFFIC_500_DELAY_JT
,DL_TRAFFIC_500_DELAY_SN
,OnlineTimeD_SN
,OnlineTimeD_JT
,ACT_BEA_REQ_CNT
,ACT_BEA_SUCC_CNT
,tcp_12sh_latency_sum
,tcp_12sh_latency_cnt
,ONLINE_USER_CNT
into tmpcount_20170907_001
from O_SE_P2P_TERMINAL_4G_H_07 where city_code=512 and hour_key=20170907070000

select count(*) from tmpcount_20170907_001

delete from O_SE_P2P_TERMINAL_4G_H_07 where city_code=512 and hour_key=20170907070000

insert into O_SE_P2P_TERMINAL_4G_H_07 select * from tmpcount_20170907_001
